on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "21.6.x"
      - name: npm install and build
        run: |
          npm install
          npm run build
      - name: Create necessary folders
        run: |
          mkdir -p dist/github-build
          mkdir -p _site
      - name: zip
        uses: thedoctor0/zip-release@main
        with:
          type: "tar"
          filename: github-build/github-pages.tar.gz
          directory: dist
          exclusions: "github-build .git"
      - name: Move artifact
        run: mv dist/github-build/github-pages.tar.gz _site/github-pages.tar.gz
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2

  deploy:
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
